version: 2.1
jobs:
  lint:
    docker:
      - image: circleci/golang:1.14.1
    steps:
      - checkout
      - run: make check-style

  build-image:
    docker:
      - image: circleci/golang:1.14.1
    steps:
      - checkout
      - setup_remote_docker
      - run: make build-image
      - run: |
          set -e
          set -u
          export TAG="${CIRCLE_SHA1:0:7}"
          #echo $DOCKER_PASSWORD | docker login --username $DOCKER_USERNAME --password-stdin
          docker tag mattermost/matterwick:test mattermost/matterwick:$TAG
          #docker push mattermost/matterwick:$TAG

  test:
    docker:
      - image: circleci/golang:1.14.1
    steps:
      - checkout
      - run: make test

workflows:
  version: 2
  pr-build:
    jobs:
      - lint
      - build-image:
          requires:
            - lint
      - test:
          requires:
            - build-image
