name: build-image

on:
  push:
    branches:
    - master
    tags:
    - "*"  # run for tags

jobs:
  build-image:
    name: build-image
    runs-on: ubuntu-latest
    steps:

    - name: checkout-repo
      uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b # v3.2.0
      with:
        fetch-depth: 0

    - name: dockerhub-login
      uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a # v2.1.0
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: build-push-tag
      uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671 # v4.0.0
      with:
        tags: mattermost/matterwick:${{ github.ref_name }}
        push: ${{ startsWith(github.ref, 'refs/tags/') }}

    - name: build-push-master
      uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671 # v4.0.0
      with:
        tags: mattermost/matterwick:latest
        push: ${{ startsWith(github.ref, 'refs/heads/master') }}
