name: build-image

on:
  push:
    branches:
    - master
    tags:
    - "*"  # run for tags


jobs:

  build-image:
    name: build-image
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2
    - name: build-push-tag
      uses: docker/build-push-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        repository: mattermost/matterwick
        tag_with_ref: true
        push: ${{ startsWith(github.ref, 'refs/tags/') }}

    - name: build-push-master
      uses: docker/build-push-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        repository: mattermost/matterwick
        tag_with_ref: true
        push: ${{ startsWith(github.ref, 'refs/heads/master') }}
